spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-one/login/oauth2/code/custom
            #redirect-uri: http://localhost:8082/ui-one/test1
            #redirect-uri: http://localhost:8082/ui-one
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/dev/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/dev/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/dev/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8083/auth/realms/dev/protocol/openid-connect/certs
            user-name-attribute: preferred_username
