spring:
  datasource:
    url: jdbc:h2:mem:customdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:schema.sql # local 프로파일용 스키마 파일 경로 설정
