server:
  port: 8081
  servlet:
    context-path: /sso-resource-server

spring:
  profiles:
    active: dev # local, dev

  # local에 설정해놔도 default로 없으면 빌드 오류 발생함
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/sample
          jwk-set-uri: http://localhost:8083/auth/realms/sample/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      # h2 로 테스트할때는 테이블이 자동 생성
      ddl-auto: none # none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true
        use-sql-comments: true
