spring:
  datasource:
    url: jdbc:h2:mem:customdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/sample
          jwk-set-uri: http://localhost:8083/auth/realms/sample/protocol/openid-connect/certs
